name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:EpitechPGE1-2025/G-DOP-200-COT-2-1-bschocolatine-3.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
