on:
  push:
    branches: [main]
jobs:
  runs-on: ubuntu-24.04
  steps:
    - name: Name
    - run: git symbolic-ref --short HEAD
    - run: du -skh --excludd=".git"
      uses: actions/checkour@v4
  
